### PR TITLE
Exporting gNMI conversion methods

### PR DESCRIPTION
**Pull request by teone**

### CODE REVIEW

**Comment by teone** [comment]
@SeanCondon @kmarquardsen can you take a look at this PR?
It exports the gNMI methods to interact with the models so that they can easily be imported in the `graphql` server.

At first sight seems like to support autogeneration the template is becoming very complex and we don't have those many models, so we might want to consider the pro/cons of supporting autogeneration for the small amount of models that we have. We might want to discuss this sometime in the future.

**Review by kmarquardsen — APPROVED** [review]

**Review by SeanCondon — APPROVED** [review]

**Comment by SeanCondon** [comment]
> At first sight seems like to support autogeneration the template is becoming very complex and we don't have those many models, so we might want to consider the pro/cons of supporting autogeneration for the small amount of models that we have. We might want to discuss this sometime in the future.

I think the advantage autogeneration gives is a clear and consistent code - I think hand editing becomes a real chore. Do you think more documentation to support the templates is warranted?

**Comment by teone** [comment]
Maybe it's me, but I don't find a 3-to-5k lines file to be very clear :) 

I think there might be some documentation/cleanup needed as:
- we have a [codegen](https://github.com/onosproject/aether-roc-api/tree/master/pkg/codegen) and a [codegenv200](https://github.com/onosproject/aether-roc-api/tree/master/pkg/codegenv200) package
- generating the `2.0.0` models creates file with the wrong reference
```
-       DeleteConnectivityServices(ctx echo.Context, target externalRef0.Target) error
+       DeleteConnectivityServices(ctx echo.Context, target Target) error
```
- generating the `top-level` api generates the wrong imports
```
-       externalRef0 "github.com/onosproject/aether-roc-api/pkg/aether_2_0_0/server"
-       externalRef1 "github.com/onosproject/aether-roc-api/pkg/aether_2_1_0/server"
-       externalRef2 "github.com/onosproject/aether-roc-api/pkg/aether_4_0_0/server"
-       externalRef3 "github.com/onosproject/aether-roc-api/pkg/app_gtwy/server"
+       externalRef0 "github.com/onosproject/aether-roc-api/pkg/aether_2_0_0/types"
+       externalRef1 "github.com/onosproject/aether-roc-api/pkg/aether_2_1_0/types"
+       externalRef2 "github.com/onosproject/aether-roc-api/pkg/aether_4_0_0/types"
+       externalRef3 "github.com/onosproject/aether-roc-api/pkg/app_gtwy/types"
```

I'm not arguing auto-generation is _bad_, I'm just saying that the current process seems a little convoluted to me (or I am simply missing something in the way it's supposed to be used). We can discuss this tomorrow during the call, I'll add a point to the agenda.

**Comment by kmarquardsen** [comment]
Definitely warrants a discussion. I was also wondering if type and conversion logic which is generated could be its own module. That way we could import it and possibly make this repo a singular versioned API eg. The module becomes '...aether-roc-api/v1'. We wouldn't need to maintain the separate server version pkgs. If you break the schema this module goes to v2. 

Another possible topic could be package orientation. As things scale particularly the number of devs on a repo I tend to favor resource oriented packages such as one for devices etc. Can help to have more contributors not conflict with each other and with planning around particular resources. Another benefit may be that if the product needs to scale it's easier to break out that 'devices' pkg into its own microservice. - more of a thought exercise but possibly worth a chat.

**Comment by SeanCondon** [comment]
@kmarquardsen if you can put together some slides for tomorrow to elaborate on your ideas a bit more it would be helpful

**Pull request merged**
